name: USP App start Tests

on:
  push:
    branches:
      - "feature/*" # matches every feature branch containing a single '/'
      - "main" # matches main branch '/'
      - "!release/**" # excludes release

jobs:
  backend-build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      - name: Build
        run: dotnet build --configuration Release USP.sln
      - name: Test
        run: dotnet test --configuration Release USP.sln --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory coverage